spring:
  profiles:
    active: development
  application:
    name: organism-ws
---
spring:
  profiles: production

---
spring:
  profiles: test
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database: postgresql
    generate-ddl: true
  datasource:
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
    platform: postgres
    driver-class-name: org.postgresql.Driver
security:
  user:
    name: admin
    password: password
eureka:
  client:
    serviceUrl:
      defaultZone: https://admin:password@discovery-service-ws.herokuapp.com/eureka
  instance:
    preferIpAddress: false
    hostname: ${DOMAIN_NAME}
    secure-port: 443

---
spring:
  profiles: development
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  datasource:
    platform: h2
server:
  use-forward-headers: true
security:
  user:
    name: admin
    password: password
